

services:
  mongo:
    image: mongo:6
    container_name: uber_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: uber_redis
    ports:
      - "6379:6379"
  
  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    container_name: uber_auth_service
    ports:
      - "3001:3000"
    env_file:
      - ./apps/auth-service/.env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis

  rider-service:
    build:
      context: .
      dockerfile: ./apps/rider-service/Dockerfile
    container_name: uber_rider_service
    ports:
      - "3002:3000"
    env_file:
      - fileName: ./apps/rider-service/.env
    volumes:
      - ./:/app
  api-gateway:
    build: 
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: uber_api_gateway
    ports:
      - "4000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - auth-service

volumes:
  mongo_data:
